spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/real-agent?connectionTimeZone=UTC&serverZoneId=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: *

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  application:
    name: real-agent-web
  ai:
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC
        # 移除stdio配置以避免启动错误
        # stdio:
        #   servers-configuration: mcp-servers-config.json
    dashscope:
      api-key: sk-***
      chat:
        options:
          model: qwen-max
    vectorstore:
      milvus:
        client:
          host: "192.168.*.*"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE

logging:
  level:
    com.ai.agent: DEBUG

# JWT 配置
jwt:

  # 访问令牌有效期（秒），默认 2 小时
  # 刷新令牌有效期（秒），默认 7 天

agent:
  action:
    tools:
      approval-mode: AUTO   # 可选：AUTO | REQUIRE_APPROVAL | DISABLED